---
- name: Install  server
  hosts: all
  vars_files:
    - "../vars/install_vars_{{ env }}.yml"
  vars:
    ansible_become_password: "{{ app_pass }}"
    hpcdb_loc: "F:\\MSSQL\\Data\\"
  become_method: runas
  become_user: "{{ app_account }}"

- hosts: all

  tasks:

  - name: Copy File

    win_copy:

      src: C:\scripts

      dest: C:\ansible_examples\
     
      remote_src: yes
