---
- hosts: all
  #connection: local
  gather_facts: yes
  vars:
    ansible_fact5:
      disks:
        - guid: 1,
          partitions:
            - drive_letter: 'A'
            - drive_letter: 'B'
        - guid: 2,
          partitions:
            - drive_letter: 'C'
            - drive_letter: 'D'
  tasks:
    - name: with_subelements -> loop
      debug:
        msg: "Disk {{ item.0.guid }} - Drive {{ item.1.drive_letter }}"
      loop: "{{ ansible_fact5.disks | subelements('partitions') }}"
