---

- name: Installing Apache MSI 

  hosts: all 

  tasks:

    - name: Download the Apache installer

      win_get_url:

        url: https://archive.apache.org/dist/httpd/binaries/win32/httpd-2.2.25-win32-x86-no_ssl.msi

        dest: C:\ansible_examples\httpd-2.2.25-win32-x86-no_ssl.msi


    - name: Install MSI
      win_command: C:\Windows\System32\msiexec.exe /i C:\ansible_examples\httpd-2.2.25-win32-x86-no_ssl.msi /qn /norestart
