
---
- hosts: all
  collections:
    - community.windows
  tasks:
   - name: Restart a service
     win_service:
       name: OpenSSH SSH Server
       state: stopped
   - name: Set timezone to 'Central Standard Time' (GMT-06:00)
     win_timezone:
       community.general.timezone: Central Standard Time



