
---
- hosts: all
  collections:
    - community.windows
  tasks:
   - name: Restart a service
     win_service:
       name: OpenSSH SSH Server
       state: stopped
   - name: Set timezone to 'Central Standard Time' (GMT-06:00)
     win_command: 'tzutil /s "Eastern Standard Time"'
 #    win_command: 'tzutil /s "Eastern Standard Time_dstoff"'
 #    community.windows.win_timezone:
 #      timezone: Central Standard Time
   - name: Set the region format to English United States
     community.windows.win_region:
       format: en-US
       copy_settings: yes

