
---
- hosts: all
  collections:
    - community.windows
  tasks:
   - name: Restart a service
     win_service:
       name: OpenSSH SSH Server
       state: stopped
   - name: Set timezone to 'Central Standard Time' (GMT-06:00)
     win_command: 'tzutil /s "Eastern Standard Time"'
 #    win_command: 'tzutil /s "Eastern Standard Time_dstoff"'
 #    community.windows.win_timezone:
 #      timezone: Central Standard Time
   - name: Set the region format to English United States
     win_region:
       format: en-US
       copy_settings: yes
       
   - name: Get product id and product key
     community.windows.win_product_facts:

   - name: Display Windows edition
     debug:
       var: ansible_os_license_edition

   - name: Display Windows license status
     debug:
       var: ansible_os_license_status

   - name: Find files in multiple paths
     ansible.windows.win_find:
       paths: C:\Temp
       recurse: yes
     register: output
     debug:
       msg: "{{  output.stdout  }}"
       #follow: yes
       #file_type: directory
#       - D:\Temp
