---
# This playbook tests the script module on Windows hosts

#- name: Run powershell script
#  hosts: all 
#  gather_facts: false
#  tasks:
#    - name: Run powershell script
#  script: files/helloworld.ps1
- name: Run multi-lined shell commands
  hosts: all
  win_shell: |
    $text = Get-Content C:\Temp\test.txt
    $text += ' General Kenobi....you are a bold one'
    Set-Content -Path C:\Temp\test2.txt -Value $text
